global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090'] ## IP Address of the localhost

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9464']

