kubeStateMetrics:
  enabled: false
nodeExporter:
  enabled: false
prometheus:
  prometheusSpec:
    enableFeatures:
      - otlp-write-receiver
grafana:
  enabled: true
  # # To make Grafana persistent (Using Statefulset)
  # #
  # persistence:
  #   enabled: true
  #   type: sts
  #   accessModes:
  #     - ReadWriteOnce
  #   size: 5Gi
  additionalDataSources:
    - name: Loki
      type: loki
      url: http://loki-gateway
      access: proxy
    - name: Tempo
      type: tempo
      url: http://tempo-query-frontend:3100
      access: proxy
