mode: deployment
replicaCount: 2
resources:
  limits:
    cpu: 2
    memory: 4Gi
  requests:
    cpu: 100m
    memory: 256Mi
image:
  repository: otel/opentelemetry-collector-k8s
command:
  name: "otelcol-k8s"

config:
  exporters:
    debug: {}
    otlp:
      endpoint: tempo-distributor:4317
      tls:
        insecure: true
    otlphttp/prometheus:
      endpoint: http://kube-prometheus-stack-prometheus:9090/api/v1/otlp
      tls:
        insecure: true

  receivers:
    jaeger: null
    prometheus: null
    zipkin: null
    otlp:
      protocols:
        grpc:
          endpoint: 0.0.0.0:4317
        http:
          endpoint: 0.0.0.0:4318
  service:
    extensions:
      - health_check
    pipelines:
      metrics:
        exporters:
          # - debug
          - otlphttp/prometheus
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
      traces:
        exporters:
          # - debug
          - otlp
        processors:
          - memory_limiter
          - batch
        receivers:
          - otlp
      logs: null

ports:
  jaeger-compact:
    enabled: false
  jaeger-thrift:
    enabled: false
  jaeger-grpc:
    enabled: false
  zipkin:
    enabled: false
